apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agrischeme

resources:
  - namespace.yaml
  - auth-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: agrischeme-pro
  app.kubernetes.io/managed-by: kustomize
